<?php
/**
 * @author Tony Xavier
 * @package Armada_ProductImport
 */

/** @var \Armada\ProductImport\Block\Adminhtml\Form\After $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div class="entry-edit fieldset" id="import_validation_container">
    <div class="entry-edit-head legend">
        <span class="icon-head head-edit-form fieldset-legend"
            id="import_validation_container_header"><?= $block->escapeHtml(__('Validation Results')) ?></span>
    </div><br>
    <div id="import_validation_messages" class="fieldset"><!-- --></div>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display:none;", 'div#import_validation_container') ?>
